"use client";

import { AuthenticationContext, AuthenticationProvider } from '@/app/context/AuthenticationContext';
import '../src/app/globals.css';
import type { Metadata } from 'next'
import React, { useContext, useEffect, useState } from "react";
import { AppProps } from 'next/app';
import LoadingScreen from '@/app/components/LoadingScreen';
import { useRouter } from 'next/router';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

const RootLayout = ({ Component, pageProps }: AppProps) => {
    const [loading, setLoading] = useState(false);
    const navigate = useRouter();

    const handleStart = () => {
        setLoading(true);
    };

    const handleComplete = () => {
        setLoading(false);
    };

    useEffect(() => {
        navigate.events.on('routeChangeStart', handleStart);
        navigate.events.on('routeChangeComplete', handleComplete);
        navigate.events.on('routeChangeError', handleComplete);

        return () => {
            navigate.events.off('routeChangeStart', handleStart);
            navigate.events.off('routeChangeComplete', handleComplete);
            navigate.events.off('routeChangeError', handleComplete);
        };
    }, [navigate.events]);

    useEffect(() => {
        if (loading) {
            document.body.style.overflowY = "hidden";
            document.documentElement.style.overflowY = "hidden";
        } else {
            document.body.style.overflowY = "auto";
            document.documentElement.style.overflowY = "auto";
        }
    }, [loading]);

    return (
        <AuthenticationProvider>
            <Component {...pageProps} />
            {loading && <LoadingScreen />}
        </AuthenticationProvider>
    );
}

export default RootLayout;